spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:sqlite:./data/ai_site.db
    driver-class-name: org.sqlite.JDBC

  flyway:
    enabled: false

logging:
  level:
    org.mydotey.ai.site: DEBUG